name: PyPI-wheel

on:
  release:
    types:
      # Note: editing the prerelease then marking as release does not trigger
      # this pipeline
      # - prereleased
      - released
  workflow_dispatch:

jobs:
  release-pypi-linux:
    runs-on: ubuntu-latest
    env:
      img: pyscf/gpu4pyscf:0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build wheels
      run: |
        docker run --rm -v ${{ github.workspace }}:/src/gpu4pyscf:rw --workdir=/src/gpu4pyscf \
        ${{ env.img }} \
        bash -exc 'sh /src/gpu4pyscf/build.sh'
    - name: List available wheels
      run: |
        ls ${{ github.workspace }}/output
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: ${{ github.workspace }}/output
        verbose: true
